#- name: Container present
#  community.docker.docker_container:
    # Get name auto
#    name: citrus_sinensis_galaxy.1.6cbgzj16lznsc4br334l5upp6
#    image: quay.io/galaxy-genome-annotation/docker-galaxy-annotation:gmod
#    state: present
#  register: galaxy_status
#- name: Get galaxy container IP
#  set_fact:
#    container_ip: "{{ galaxy_status.ansible_facts.docker_container.NetworkSettings.IPAddress }}"
#- name: Check container status
#  wait_for:
#    host: "{{ container_ip }}"
#    port: 8888

#- name: Check galaxy service status
#  community.docker.docker_swarm_service:
#  docker_swarm_service:
    # Get name auto
#    name: citrus_sinensis_galaxy
#    image: quay.io/galaxy-genome-annotation/docker-galaxy-annotation:gmod    
#    healthcheck:
      # Check if nginx server is healthy by curl'ing the server.
      # If this fails or timeouts, the healthcheck fails.
#      test: ["CMD", "curl", "--fail", "http://nginx.host.com"]
#      interval: 2m30s
#      timeout: 10s
#      retries: 5
#      start_period: 30s

- name: Run gga_load_data script
  command: "python3 {{ gga_load_data }} {{ input_sp }} --config {{ config_file }}"
  args:
    chdir: "{{ repo_folder }}"
