- hosts: os_vms
  become: yes
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: yes
        cache_valid_time: 86400
      when:
        - ansible_os_family == 'Debian'
  roles:
    - gga
