- hosts: os_vms
  become: yes
  pre_tasks:
    # Update and upgrade librairies
    - name: Allow release-info to change for APT repositories
      apt:
        update_cache: yes
        #allow_releaseinfo_change: True
    - name: Apt upgrade
      apt:
        upgrade: safe
  roles:
    - abims-sbr.gga_install