- name: Clone GGA repository
  ansible.builtin.git:
    repo: "{{ repo_name }}"
    dest: "{{ repo_folder }}"
    version: "{{ gga_load_data_version }}"
    accept_hostkey: yes
    force: yes
    recursive: no

- name: Installing python libraries
  pip:
    executable: pip3
    requirements: "{{ repo_folder }}/requirements.txt"
