# Build config template files

- name: Generate configuration template
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ repo_folder }}/config.yml"
    mode: "u=rw,g=r,o=r"

- name: Generate input template
  ansible.builtin.template:
    src: input.yml.j2
    dest: "{{ repo_folder }}/input.yml"
    mode: "u=rw,g=r,o=r"

# Initialize GGA
- name: Run gga_init script
  command: "python3 {{ repo_folder }}/{{ gga_init }} {{ input_sp }} --config {{ config_file }} --force-traefik"
  args:
    chdir: "{{ repo_folder }}"
  become: yes
