---

# terraform directory
terraform_dir: "{{ playbook_dir }}/terraform" # Where your terraform folder will be build.

# ssh_cfg.tmpl file
ssh_key_path: ~/.ssh/id_rsa.pub

# Openstack (os)

## var.tf variables
os_auth_url: "" # The Identity authentication URL.
os_project_id: "" # The ID of the Tenant (v2) or Project (v3).
os_project_name: "" # The Name of the Tenant (v2) or Project (v3).
os_user_domain_name: "" # The domain name where the user is located.
os_project_domain_id: "" # The domain ID where the project is located.
os_username: "" # The Username to login with.
os_password: "" # The Password used to log in to your cloud account.
os_network: "" # The name of the network.

## resource.tf variables
vm_name: "GGA" # A unique name for the resource.
vm_image_name: "vm_image_name" # The name of the desired image for the resource. (Required if vm_image_id is empty).
vm_image_id: "" # The image ID of the desired image for the resource. (Required if vm_image_name is empty).
vm_flavor_name: "vm_flavor_name" # The name of the desired flavor for the resource.
vm_key_pair: "" # The name of a key pair to put on the resource. The key pair must already be created and associated with the tenant's (v2) or project's (v3) account.
vm_security_group: "" # An array of one or more security group names to associate with the server.

# To create and attach a volume to the instance
#vol_name: "volume_name" # A unique volume name.
#vol_size: "5" # The size of the volume to create (in gigabytes).
#vol_type: "" # The type of volume to create.

# To attach an existing volume
#vol_id: "volume_id" # An existing volume id.

# hosts.tmpl template variable
os_vms_user: "root"
